FROM node:22-alpine AS deps

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

FROM node:22-alpine AS builder

ARG SITE_URL=https://tickward.com
ARG NEXT_PUBLIC_TICKWARD_MAX_TIMERS=20
ARG NEXT_PUBLIC_TICKWARD_MAX_TIMERS_PER_SPACE=20
ARG NEXT_PUBLIC_TICKWARD_MAX_PROJECTS=10
ARG NEXT_PUBLIC_TICKWARD_MAX_SPACES=2
ARG NEXT_PUBLIC_PLAUSIBLE_URL=
ARG NEXT_PUBLIC_PLAUSIBLE_DOMAIN=

ENV NEXT_TELEMETRY_DISABLED=1
ENV SITE_URL=$SITE_URL
ENV NEXT_PUBLIC_TICKWARD_MAX_TIMERS=$NEXT_PUBLIC_TICKWARD_MAX_TIMERS
ENV NEXT_PUBLIC_TICKWARD_MAX_TIMERS_PER_SPACE=$NEXT_PUBLIC_TICKWARD_MAX_TIMERS_PER_SPACE
ENV NEXT_PUBLIC_TICKWARD_MAX_PROJECTS=$NEXT_PUBLIC_TICKWARD_MAX_PROJECTS
ENV NEXT_PUBLIC_TICKWARD_MAX_SPACES=$NEXT_PUBLIC_TICKWARD_MAX_SPACES
ENV NEXT_PUBLIC_PLAUSIBLE_URL=$NEXT_PUBLIC_PLAUSIBLE_URL
ENV NEXT_PUBLIC_PLAUSIBLE_DOMAIN=$NEXT_PUBLIC_PLAUSIBLE_DOMAIN
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run db:download-rds-ca
RUN npm run build
RUN npm prune --omit=dev

FROM node:22-alpine AS runner

ARG SITE_URL=https://tickward.com
ARG NEXT_PUBLIC_TICKWARD_MAX_TIMERS=20
ARG NEXT_PUBLIC_TICKWARD_MAX_TIMERS_PER_SPACE=20
ARG NEXT_PUBLIC_TICKWARD_MAX_PROJECTS=10
ARG NEXT_PUBLIC_TICKWARD_MAX_SPACES=2
ARG NEXT_PUBLIC_PLAUSIBLE_URL=
ARG NEXT_PUBLIC_PLAUSIBLE_DOMAIN=

ENV HOSTNAME=0.0.0.0
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV SITE_URL=$SITE_URL
ENV NEXT_PUBLIC_TICKWARD_MAX_TIMERS=$NEXT_PUBLIC_TICKWARD_MAX_TIMERS
ENV NEXT_PUBLIC_TICKWARD_MAX_TIMERS_PER_SPACE=$NEXT_PUBLIC_TICKWARD_MAX_TIMERS_PER_SPACE
ENV NEXT_PUBLIC_TICKWARD_MAX_PROJECTS=$NEXT_PUBLIC_TICKWARD_MAX_PROJECTS
ENV NEXT_PUBLIC_TICKWARD_MAX_SPACES=$NEXT_PUBLIC_TICKWARD_MAX_SPACES
ENV NEXT_PUBLIC_PLAUSIBLE_URL=$NEXT_PUBLIC_PLAUSIBLE_URL
ENV NEXT_PUBLIC_PLAUSIBLE_DOMAIN=$NEXT_PUBLIC_PLAUSIBLE_DOMAIN
ENV PORT=3000

WORKDIR /app
RUN addgroup -S nextjs && adduser -S nextjs -G nextjs

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts ./prisma.config.ts
COPY --from=builder /app/public ./public

USER nextjs
EXPOSE 3000

CMD ["sh", "-c", "npm run db:migrate:deploy && npm run start"]
