export const ADMIN_COPY = {
  metaTitle: "Admin statistics",
  metaDescription: "Read-only private operating statistics for Tickward.",
  heading: "Admin statistics",
  intro: "A private read-only snapshot of accounts, usage, integrations, and notification delivery.",
  generatedAt: (value: string) => `Generated ${value}`,
  sections: {
    users: {
      heading: "Users",
      description: "Account growth, bans, and active session coverage.",
    },
    usage: {
      heading: "Product usage",
      description: "Timer, project, share, and push subscription activity.",
    },
    integrations: {
      heading: "Integrations & API",
      description: "API credentials, authorization grants, and webhook endpoint health.",
    },
    notifications: {
      heading: "Notification health",
      description: "Outbox state, delivery results, webhook delivery results, and recent failures.",
    },
  },
  metrics: {
    usersTotal: "Total users",
    usersNew7d: "New users",
    usersNew30d: "New users",
    usersBanned: "Banned users",
    activeSessions: "Active sessions",
    timersActive: "Active timers",
    timersArchived: "Archived timers",
    projectsOwned: "Owned projects",
    projectsOwnerless: "Ownerless projects",
    sharesTotal: "Shares",
    pushSubscriptionsActive: "Active push subscriptions",
    apiKeysActive: "Active API keys",
    apiKeysRevoked: "Revoked API keys",
    apiKeysUsed7d: "API keys used",
    mcpGrantsActive: "Active MCP grants",
    deviceGrantsActive: "Active device grants",
    outboxPending: "Pending outbox items",
    webhookFailures7d: "Webhook failures",
    deliveryFailures7d: "Delivery failures",
  },
  metricDetails: {
    last7d: (value: string) => `${value} last 7 days`,
    last30d: (value: string) => `${value} last 30 days`,
    activeNow: "Expires after the generated time.",
    activeTotal: (value: string) => `${value} total grants`,
    successfulDeliveries: (value: string) => `${value} successful deliveries`,
  },
  charts: {
    dailySignups: "Daily signups",
    dailyTimersCreated: "Daily timers created",
    dailySignupsAria: "Daily signups for the last 30 days",
    dailyTimersCreatedAria: "Daily timers created for the last 30 days",
  },
  tables: {
    apiKeysByKind: {
      heading: "API keys by kind",
      caption: "API key records grouped by kind.",
      empty: "No API keys recorded.",
    },
    webhookEndpointsByStatus: {
      heading: "Webhook endpoints by status",
      caption: "Webhook endpoint records grouped by status.",
      empty: "No webhook endpoints recorded.",
    },
    deliveryByChannel7d: {
      heading: "Delivery log by channel",
      caption: "Notification delivery logs grouped by channel and status for the last 7 days.",
      empty: "No delivery logs in the last 7 days.",
    },
    outboxByStatus: {
      heading: "Outbox by status",
      caption: "Notification outbox items grouped by status.",
      empty: "No outbox items recorded.",
    },
    webhookDeliveriesByStatus7d: {
      heading: "Webhook deliveries by status",
      caption: "Webhook delivery records grouped by status for the last 7 days.",
      empty: "No webhook deliveries in the last 7 days.",
    },
    recentWebhookFailures: {
      heading: "Recent webhook failures",
      caption: "Most recent failed webhook deliveries.",
      empty: "No failed webhook deliveries recorded.",
      noResponseStatus: "No response",
      noFailureDate: "No failure date",
    },
    columns: {
      kind: "Kind",
      status: "Status",
      channel: "Channel",
      count: "Count",
      success: "Success",
      failure: "Failure",
      endpointId: "Endpoint ID",
      response: "Response",
      failedAt: "Failed at",
      attempts: "Attempts",
    },
  },
} as const
